### ISSUE TITLE
Add support for 2FA

### ISSUE THREAD

**Issue by muxa** [NickWaterton/Unifi-websocket-interface#1]
I'm using UDM and my account has 2FA enabled.
When trying to connect to UDM I'm getting the following error:
```
PS ...\Code\Unifi-websocket-interface> python unifi_client.py -D -po 443  192.168.1.1 <email> <password>
Debug mode
Unifi OS controller detected
Python: sys.version_info(major=3, minor=8, micro=2, releaselevel='final', serial=0)
Python: sys.version_info(major=3, minor=8, micro=2, releaselevel='final', serial=0)
Python 3 websocket
login() https://192.168.1.1/proxy/network/ as <email>
failed to connect: 
Exited
```
It keeps trying to connect in a loop.

Without 2FA it connects and pulls events fine. 

It would be great to be able to auth with additional 2FA token passed via command line so that this tool works with increased security setups.

UDM Info:
* Firmware: 1.7.0.2614
* Controller Version: 5.13.27

**Comment by muxa** [comment]
Ignore that. 
Having a manual 2FA in this tool will make it difficult to automatic things. 
What I did instead is created a local user under `/users/users` with Read Only access and use its username/password with the tool. Worked like a charm!

**Comment by NickWaterton** [comment]
No problem, that's probably a much better idea anyway.
